#!/bin/bash

REPORT="zeek_security_report_$(date +%Y%m%d_%H%M%S).txt"

cat > "$REPORT" << EOF
================================================================================
 NETWORK SECURITY ANALYSIS REPORT
Generated by Zeek
================================================================================
Report Date: $(date)
Analysis Period: Network traffic capture session
Analyst: Lab Student

EXECUTIVE SUMMARY
-----------------
This report presents the findings from network traffic analysis using Zeek
(formerly Bro) network security monitor. The analysis focused on detecting
malicious activities, suspicious patterns, and potential security threats.

METHODOLOGY
-----------
1. Network traffic capture using Zeek on local interface
2. Custom script deployment for threat detection
3. Log analysis and pattern recognition
4. Forensic timeline reconstruction
5. Security assessment and recommendations

FINDINGS
--------
EOF

if [ -f malicious_activity.log ]; then
    echo "Security Alerts Detected: YES" >> "$REPORT"
    echo "Total Alerts: $(wc -l < malicious_activity.log)" >> "$REPORT"
else
    echo "Security Alerts Detected: NO" >> "$REPORT"
fi

cat >> "$REPORT" << EOF

TRAFFIC STATISTICS
------------------
EOF

if [ -f conn.log ]; then
    echo "Total Connections: $(grep -c '^{' conn.log)" >> "$REPORT"
fi

if [ -f dns.log ]; then
    echo "DNS Queries: $(grep -c '^{' dns.log)" >> "$REPORT"
fi

if [ -f http.log ]; then
    echo "HTTP Requests: $(grep -c '^{' http.log)" >> "$REPORT"
fi

cat >> "$REPORT" << EOF

SECURITY RECOMMENDATIONS
------------------------
1. Continue monitoring with Zeek
2. Update detection signatures
3. Investigate flagged alerts
4. Implement network segmentation
5. Maintain security baselines

CONCLUSION
----------
The Zeek network security monitoring system successfully captured and analyzed
network traffic, providing valuable insights into network behavior and potential
security threats. The custom detection scripts demonstrated effective capability
in identifying suspicious activities and generating actionable security alerts.
Regular deployment of such monitoring tools is essential for maintaining
network security posture and enabling rapid incident response.

================================================================================
 END OF REPORT
================================================================================
EOF

echo "Report generated: $REPORT"
head -30 "$REPORT"
